Repository Team-ComIT/SimTong-Backend, pull requests merged in 2022-10, with the labels that each got.

#95 merge: (#94) 닉네임 변경
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeNicknameRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/error/AuthErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/UsedNicknameException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeNicknameRequest.kt
Labels: feat

#93 merge: (#88) 비밀번호 초기화 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ResetPasswordRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/error/AuthErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/RequiredNewEmailAuthenticationException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebResetPasswordRequest.kt
Labels: feat

#97 merge: (#96) 이메일 변경 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeEmailRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeEmailRequest.kt
Labels: feat

#105 merge: (#84) 로그인 안된 상태에서 메뉴 조회
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/menu/WebMenuAdapter.kt
Labels: feat

#110 merge: (#98) Data class & Role 수정
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/RefreshToken.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/model/Menu.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/model/Spot.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/model/Team.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
Labels: bug, refactor

#112 merge: (#90) Redis Repository 문제 해결
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetailsService.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeLimitEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/RefreshTokenEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodeLimitRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodeRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/RefreshTokenRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESAdapter.kt
Labels: bug

#113 merge: (#109) 비밀번호 초기화 변경 사항
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
Labels: refactor

#114 merge: (#111) 회원 가입 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/Policy.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/GlobalComponentScan.kt
Labels: refactor

#117 merge: (#103) 비밀번호 변경 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangePasswordRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebChangePasswordRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebResetPasswordRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebSignUpRequest.kt
Labels: feat

#119 merge: (#118) 이메일 중복 검사 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckEmailDuplicationUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckEmailDuplicationUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
Labels: feat

#120 merge: (#115) 지점 변경 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryRefreshTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/RefreshTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserJwtPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryAuthCodeLimitPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryAuthCodePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuQueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuSecurityPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/NickNamePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQueryAuthCodeLimitPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQuerySpotPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQueryTeamPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserSecurityPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeSpotRequest.kt
Labels: feat, refactor

#121 merge: (#116) 닉네임 중복 검사 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
Labels: feat

#125 merge: (#122) regex util
  simtong-presentation/src/main/kotlin/team/comit/simtong/RegexUtil.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebChangePasswordRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebResetPasswordRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebChangeNicknameRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebSignUpRequest.kt
Labels: refactor

#126 merge: (#123) Request Dto 명 변경
  simtong-presentation/src/main/kotlin/team/comit/simtong/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/ChangePasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/FindEmployeeNumberWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/ResetPasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/response/FindEmployeeNumberWebResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/email/WebEmailAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/email/dto/request/CheckAuthCodeWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/email/dto/request/SendAuthCodeWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/file/WebFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/file/dto/response/UploadImageListWebResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/file/dto/response/UploadImageWebResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeEmailWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeNicknameWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeProfileImageWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/ChangeSpotWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/SignUpWebRequest.kt
Labels: docs

#127 merge: (#124) 이름 & 이메일 계정 여부 확인 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/CheckMatchedAccountRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/CheckMatchedAccountWebRequest.kt
Labels: feat

#129 merge: (#128) 지점 리스트
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/dto/SpotResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/spi/QuerySpotPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
Labels: feat

#131 merge: (#130) 사원번호 & 이메일 계정 여부 확인 수정
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/CheckMatchedAccountRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/CheckMatchedAccountWebRequest.kt
Labels: refactor

#133 merge: (#132) 도메인 모델 환경변수 적용
  .gitignore
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/build.gradle.kts
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainProperties.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
  simtong-domain/src/main/resources/domain.properties
Labels: defer, refactor

#135 merge: hotfix gitignore 수정
  .gitignore
  simtong-domain/src/main/resources/domain.properties
Labels: setting

#136 merge: (#134) InputS3 매개변수 정리
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/storage/AwsS3Adapter.kt
Labels: refactor
