Repository Team-ComIT/SimTong-Backend, pull requests merged in 2022-09, with the labels that each got.

#21 merge: (#20) Jacoco 설정
  .github/workflows/CI.yml
  .github/workflows/build.yml
  build.gradle.kts
  codecov.yml
Labels: setting

#30 merge: (#29) 주석 수정
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/ReceiveTokenPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/RedisConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/FilterConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/JwtFilter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/error/SecurityErrorCode.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/ExpiredTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/UnexpectedTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/WrongTypeTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtComponent.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtParser.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodePolicyEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/RefreshTokenEntity.kt
Labels: docs

#24 merge: (#23) Jwt Filter 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/ReceiveTokenPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/RedisConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/FilterConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/JwtFilter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/error/SecurityErrorCode.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/ExpiredTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/UnexpectedTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/WrongTypeTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtComponent.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/JwtParser.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodePolicyEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/RefreshTokenEntity.kt
Labels: feat, setting

#27 merge: (#25) 회원 가입 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/ReceiveTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/dto/TokenResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/SaveUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/dto/DomainSignUpRequest.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/UserErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/UsedEmailException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/UserNotFoundException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/CheckEmailPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/CheckEmployeePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/NickNamePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/SecurityPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/Policy.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/GlobalComponentScan.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/JwtFilter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/GenericMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/auth/dto/request/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/auth/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/auth/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/auth/dto/request/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/auth/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/WebSignUpRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
Labels: feat

#37 merge: signup policy
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/CheckEmailPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/CheckEmployeePort.kt
Labels: refactor

#40 merge: (#26) ErrorResponse 형식
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/CustomFieldError.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/ErrorResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
Labels: bug, refactor

#41 merge: (#38) Transaction 적용 모듈 변경
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  buildSrc/src/main/kotlin/PluginVersions.kt
  simtong-application/build.gradle.kts
  simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/ReadOnlyUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/UseCase.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/TransactionAspect.kt
Labels: refactor

#45 merge: (#32) 로그인 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/dto/SignInRequest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/user/usecase/SignInUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/UserErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/DifferentPasswordException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaProvider.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/WebSignInRequest.kt
Labels: feat, refactor

#49 merge: (#34) 회원가입 정책 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/dto/.gitkeep
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/dto/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/error/AuthErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/UncertifiedEmailException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/UsedEmailException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodePolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/DomainQueryAuthCodePolicyPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/UserErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/DomainQueryUserPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/AuthCodePolicyMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodePolicyRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodeRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/RefreshTokenRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/extension/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
Labels: feat, test

#60 merge: (#55) AuthCodePolicy 테이블 변경
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/DomainQueryAuthCodeLimitPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/DomainQueryAuthCodePolicyPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeLimitEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/AuthCodeLimitMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/AuthCodePolicyMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodeLimitRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/AuthCodePolicyRepository.kt
Labels: refactor

#61 merge: (#59) Exception 설계 리팩터링
  codecov.yml
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/SaveUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/GenericMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/AuthCodeLimitMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaProvider.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
Labels: refactor

#56 merge: (#54) 사원 번호 찾기
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/dto/FindEmployeeNumberRequest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetailsService.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/DeviceTokenJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/auth/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/auth/dto/request/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/auth/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/WebFindEmployeeNumberRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/response/WebFindEmployeeNumberResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/WebSignUpRequest.kt
Labels: feat

#66 merge: (#58) 토큰 재발급 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/QueryRefreshTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/error/AuthErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/RefreshTokenNotFoundException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/RefreshToken.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/RefreshTokenMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/repository/RefreshTokenRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
Labels: feat

#65 merge: (#64) User & Spot 연관관계 설계
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/dto/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/error/SpotErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/exception/SpotNotFoundException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/model/Spot.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/service/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/spi/DomainQuerySpotPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
Labels: feat

#73 merge: (#70) 누락된 Adapter 설계
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/mapper/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/mapper/SpotMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt
Labels: feat

#72 merge: (#67) port dependency
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/JwtPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/ReceiveTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/RefreshTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/exception/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserJwtPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/DomainQueryAuthCodeLimitPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/spi/DomainQuerySpotPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/DomainQueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQueryAuthCodeLimitPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQuerySpotPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserSecurityPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
Labels: refactor

#74 merge: (#67) additional port dependency
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/spi/.gitkeep
Labels: refactor

#69 merge: (#68) User & Team 연관관계 세팅
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/RefreshTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/exception/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/spi/TeamPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/usecase/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserJwtPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/dto/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/error/TeamErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/exception/TeamNotFoundException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/model/Team.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/service/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/UserQueryTeamPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/mapper/SpotMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/entity/TeamJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/DeviceTokenJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
Labels: feat

#76 merge: (#75) module architecture
  simtong-application/build.gradle.kts
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/dto/TokenResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/usecase/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/FindEmployeeNumberRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignUpRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserJwtPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/dto/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/policy/SignUpPolicy.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/SimtongApplication.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/GlobalErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/CustomFieldError.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/token/GenerateJwtAdapter.kt
  simtong-infrastructure/src/main/resources/application.yml
  simtong-presentation/build.gradle.kts
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/request/WebFindEmployeeNumberRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/common/dto/response/WebFindEmployeeNumberResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebSignInRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/request/WebSignUpRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/user/dto/response/.gitkeep
Labels: refactor

#83 merge: (#80) menu 조회
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/MenuResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuQueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuSecurityPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/QuerydslConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/repository/MenuJpaRepository.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/menu/WebMenuAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/menu/dto/request/.gitkeep
Labels: feat
