Repository Team-ComIT/SimTong-Backend, pull requests merged in 2022-08, with the labels that each got.

#5 merge: (#4) github 설계
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/do.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
Labels: setting

#6 merge: (#3) persistence model 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/error/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/exception/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/dto/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/service/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseTimeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseUUIDEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/entity/SpotJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/mapper/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/entity/TeamJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/DeviceTokenJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/DeviceTokenJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/.gitkeep
  simtong-presentation/src/main/resources/application.yml
Labels: feat

#12 merge: (#8) Exception 아키텍처 설계
  simtong-domain/src/main/kotlin/team/comit/simtong/global/error/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/global/error/BusinessException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/error/ErrorProperty.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/GlobalErrorCode.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/GlobalErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/exception/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/exception/InternalServerErrorException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
  simtong-presentation/build.gradle.kts
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
Labels: setting

#14 merge: (#13) Issue Template & Pull-request Template 수정
  .github/ISSUE_TEMPLATE/do.yml
  .github/ISSUE_TEMPLATE/fix.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseTimeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/BaseUUIDEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/entity/SpotJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/entity/TeamJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/DeviceTokenJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/DeviceTokenJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
Labels: refactor, setting

#15 merge: (#10) Annotation 구성 설계
  simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/ReadOnlyUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/global/annotation/UseCase.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/Aggregate.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/annotation/DomainService.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/TransactionAspect.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/aop/UseCaseScan.kt
Labels: feat

#11 merge: (#7) NoSQL 모델 설계
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/RedisConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePolicyRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodeEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/entity/AuthCodePolicyEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/.gitkeep
  simtong-presentation/src/main/resources/application.yml
Labels: feat, refactor

#19 merge: (#9) Security 설계
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/ConfigurationPropertiesConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/FilterConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityProperties.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/error/SecurityErrorCode.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/exception/InvalidTokenException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetails.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/principle/AuthDetailsService.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserJpaRepository.kt
  simtong-presentation/src/main/resources/application.yml
Labels: setting
