Repository Team-ComIT/SimTong-Backend, pull requests merged in 2022-12, with the labels that each got.

#163 merge: (#162) 메뉴 엔티티 수정
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/spot/model/Spot.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuId.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/resources/application.yml
Labels: refactor

#165 merge: (#164) 휴무일 설계
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/error/HolidayErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayType.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/service/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayId.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/repository/MenuJpaRepository.kt
Labels: feat

#168 merge: (#166) 개인 + 일정 조회 API
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/QueryEntireSpotScheduleResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/QueryIndividualSpotScheduleResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt
Labels: feat

#170 merge: (#169) 휴무일 지정 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/error/HolidayErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/WeekHolidayLimitExcessException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayQueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidaySecurityPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/QuerydslExtensionUtils.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/resources/application.yml
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/AppointHolidayWebRequest.kt
Labels: feat

#173 merge: (#171) Query 코드 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/exception/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleSecurityPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
Labels: refactor

#175 merge: (#174) 휴무일 또는 연차 취소 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/error/HolidayErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/HolidayNotFoundException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/CancelHolidayWebRequest.kt
Labels: feat

#180 merge: (#177) 이메일 전송 비동기
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESConfig.kt
Labels: performance, refactor

#181 merge: (#176) 개인 휴무일 조회 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryIndividualHolidaysResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt
Labels: feat

#183 merge: (#182) 비밀번호 일치 여부 기능 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ComparePasswordUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ComparePasswordUseCaseTests.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
Labels: feat

#189 merge: (#186) 직원 명부 Entity 설계
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/CommandEmployeeCertificatePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/EmployeeCertificatePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/model/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/model/EmployeeCertificate.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificateJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/entity/EmployeeCertificateJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/mapper/EmployeeCertificateMapper.kt
Labels: feat, setting

#190 merge: (#184) 인증 완료 후 인증코드 제한 삭제
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/AuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserCommandAuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
Labels: refactor

#192 merge: (#191) 이름, 사원번호 일치 여부 확인 API
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/EmployeeCertificatePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/CheckEmployeeUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/CheckEmployeeUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/error/FileErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/exception/InvalidEmployeeException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/spi/QueryEmployeeCertificatePort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificateJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
Labels: feat

#193 merge: (#187) 사원 명부 저장 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/CommandEmployeeCertificatePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/ParseFilePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/RegisterEmployeeCertificateUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/RegisterEmployeeCertificateUseCaseTest.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/FileExtensionUtils.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/error/FileErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/exception/FileNotValidContentException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/parser/ExcelFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt
Labels: feat

#198 merge: (#196) Aggregate Mapping 코드 스타일 변경
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/RefreshTokenPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
Labels: refactor

#201 merge: (#199) S3 등록된 이미지 접근 오류
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/storage/AwsS3Adapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt
Labels: refactor

#203 merge: (#202) MultipartFile → File 변환 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/FileExtensionUtils.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/error/FileErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/exception/FileInvalidExtensionException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/error/WebFileErrorCode.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/exception/FileInvalidExtensionException.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/transfer/ExcelFileConvertor.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/transfer/FileConvertor.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/transfer/ImageFileConvertor.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/error/WebErrorProperty.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/error/WebException.kt
Labels: performance, refactor

#205 merge: (#197) EmployeeCertificate 관련 리팩터링
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/file/model/EmployeeCertificate.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/parser/ExcelFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/converter/ExcelFileConverter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/converter/FileConverter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/converter/FileExtensions.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/converter/ImageFileConverter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/transfer/ImageFileConvertor.kt
Labels: refactor

#206 merge: (#204) 지점 + 개인 일정 보기 변경사항
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/QueryIndividualSpotScheduleResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
Labels: bug, refactor

#207 merge: (#188) 메뉴 저장 API
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/ParseEmployeeCertificateFilePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/RegisterEmployeeCertificateUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/CommandMenuPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/ParseMenuFilePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/RegisterEmployeeCertificateUseCaseTest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/error/MenuErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/exception/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/exception/MenuAlreadyExistsSameMonthException.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/parser/ExcelFileAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/storage/AwsS3Adapter.kt
  simtong-infrastructure/src/main/resources/application-dev.yml
  simtong-infrastructure/src/main/resources/application-prod.yml
  simtong-infrastructure/src/test/kotlin/team/comit/simtong/thirdparty/storage/AwsS3AdapterTests.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/WebMenuAdapter.kt
Labels: feat

#211 merge: (#210) 관리자 정보 불러오기 기능 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/QueryAdminInfoResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/QueryUserInfoResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/QueryAdminInfoUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/QueryUserInfoUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/QueryAdminInfoUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/QueryUserInfoUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
Labels: feat

#209 merge: (#208) License 추가
  LICENSE
Labels: docs

#219 merge: (#218) Security Policy 작성
  SECURITY.md
Labels: docs

#217 merge: (#216) 정규표현식 수정
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ChangePasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ResetPasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/ChangeNicknameWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtil.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtils.kt
Labels: bug, refactor

#221 merge: (#220) CD 실행 시 Health Check
  .github/workflows/stage-cd.yml
  Dockerfile
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/HealthCheckWebAdapter.kt
Labels: setting

#222 merge: (#216) 정규식 최적화
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ResetPasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtils.kt
Labels: refactor

#229 merge: (#228) 회원가입시 사원번호 검사 추가
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/exception/AuthExceptions.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/QueryUserPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/UserJpaRepository.kt
Labels: refactor

#226 merge: (#224) 기간 매개변수 변경
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/SaveMenuRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/QueryMenuPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/WebMenuAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/dto/request/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/dto/request/SaveMenuWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt
Labels: refactor

#232 merge: (#231) 남은 연차 개수 기능 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryRemainAnnualUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryQueryRemainAnnualUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/QuerydslExtensionUtils.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/response/QueryRemainAnnualWebResponse.kt
Labels: feat

#234 merge: (#232) api http method
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
Labels: refactor

#237 merge: (#236) query team api
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/dto/QueryTeamsResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/spi/TeamPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/usecase/QueryTeamsUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/team.usecase/QueryTeamsUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/team/spi/QueryTeamPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
Labels: feat

#238 merge: (#235) 휴무일 작성 기간 Aggregate 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayPeriod.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayStatus.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayPeriodId.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayPeriodJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayPeriodMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/repository/HolidayJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/repository/HolidayPeriodJpaRepository.kt
Labels: feat, refactor

#242 merge: (#239) 기능 명세 추가로 인한 변경
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryIndividualRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayPeriodPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/HolidayExceptions.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayStatus.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPeriodPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/QuerydslExtensionUtils.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayId.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayPeriodId.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayPeriodJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayPeriodMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/repository/HolidayJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/repository/HolidayPeriodJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuId.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/entity/MenuJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/repository/MenuJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/entity/ScheduleJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/entity/SpotJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/DeviceTokenJpaEntity.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/WebHolidayStatus.kt
Labels: feat, refactor

#244 merge: (#243) prod CD
  .github/workflows/prod-cd.yml
Labels: feat

#247 merge: (#241) 휴무표 공유 API
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/ShareHolidayWebRequest.kt
Labels: feat

#246 merge: (#245) 휴무일 & 연차 제약조건 추가
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/exception/HolidayExceptions.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayStatus.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
Labels: feat, refactor

#252 merge: (#248) 지점 직원 휴무일 보기 API
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryEmployeeHolidayResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayQueryType.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/vo/EmployeeHoliday.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/vo/EmployeeHolidayVO.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/WebHolidayQueryType.kt
Labels: feat

#250 merge: (#249) 휴무표 작성 기간 확인 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPeriodPort.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/entity/HolidayJpaEntity.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
Labels: feat

#254 merge: (#251) 휴무표 작성 기간 설정 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/AppointHolidayPeriodRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPeriodPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/HolidayPeriodPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayPeriodUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayPeriodUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryRemainAnnualUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/AppointHolidayPeriodWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/CancelHolidayWebRequest.kt
Labels: feat

#256 merge: (#255) 휴무표 작성 기간 보기 기능
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/dto/QueryMonthHolidayPeriodResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryMonthHolidayPeriodUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryMonthHolidayPeriodUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
Labels: feat

#257 merge: (#253) 지점 직원 휴무일 변경
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/request/ChangeEmployeeHolidayWebRequest.kt
Labels: feat

#258 redis password 설정
  simtong-infrastructure/src/main/resources/application-dev.yml
  simtong-infrastructure/src/main/resources/application-prod.yml
Labels: bug

#259 merge: (#178) FCM 전송
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmConfig.kt
  simtong-infrastructure/src/main/resources/application-dev.yml
  simtong-infrastructure/src/main/resources/application-prod.yml
Labels: feat

#262 merge: (#260) Notification Model 설계
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/exception/NotificationExceptions.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/Notification.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/NotificationReceiver.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/NotificationType.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/entity/NotificationJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/entity/NotificationReceiverJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationReceiverMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/repository/NotificationJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/repository/NotificationReceiverRepository.kt
Labels: feat

#263 merge: (#261) 알림 저장
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/exception/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/CommandNotificationPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/NotificationPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/NotificationQueryUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/SendPushMessagePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/usecase/SendNotificationUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/Notification.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/notification/model/NotificationReceiver.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/NotificationPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/repository/NotificationReceiverJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/repository/DeviceTokenJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/NotificationWebAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/SendNotificationWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/WebNotificationType.kt
Labels: feat
