Repository Team-ComIT/SimTong-Backend, pull requests merged in 2022-11, with the labels that each got.

#138 merge: (#137) 일정 Aggregate
  buildSrc/src/main/kotlin/Dependencies.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/exception/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/SchedulePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/error/ScheduleErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/exception/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/model/Schedule.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/model/Scope.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/service/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/.gitkeep
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/ScheduleJpaRepository.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/entity/ScheduleJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/mapper/ScheduleMapper.kt
Labels: feat, setting

#140 merge: (#139) 지점 일정 추가 기능 설계
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodeLimitPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/CommandAuthCodePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SecurityPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/AddSpotScheduleRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/CommandSchedulePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/SchedulePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/.gitkeep
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandUserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/menu/spi/MenuQueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/.gitkeep
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleQueryUserPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleSecurityPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/error/UserErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/exception/NotEnoughPermissionException.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Authority.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/WebScheduleAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/dto/request/AddSpotScheduleWebRequest.kt
Labels: feat

#145 merge: (#144) CD 구축
  .github/workflows/stage-cd.yml
  Dockerfile
Labels: feat

#146 merge: (#143) 지점 일정 삭제 기능
  Dockerfile
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/spi/CommandSchedulePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/WebScheduleAdapter.kt
Labels: feat

#148 merge: (#147) Domain Properties 에러
  simtong-application/src/test/kotlin/team/comit/simtong/domain/DomainPropertiesInitialization.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainProperties.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/error/DomainErrorCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/exception/NotInitializationPropertiesException.kt
  simtong-domain/src/main/resources/domain.properties
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/config/DomainPropertiesConfig.kt
  simtong-infrastructure/src/main/resources/application.yml
Labels: bug

#151 merge: (#149) 전체 지점 일정 조회
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/EntireSpotScheduleResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/EntireSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/spi/SpotPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/.gitkeep
  simtong-application/src/test/kotlin/team/comit/simtong/domain/DomainPropertiesInitialization.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/EntireSpotScheduleUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/QuerySchedulePort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/spi/ScheduleQuerySpotPort.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/vo/SpotSchedule.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/global/DomainPropertiesPrefix.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/vo/SpotScheduleVo.kt
  simtong-infrastructure/src/main/resources/application.yml
Labels: feat

#154 merge: (#153) 개인 일정 추가
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/dto/AddIndividualScheduleRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/AddIndividualScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddIndividualScheduleUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/schedule/dto/request/AddIndividualScheduleWebRequest.kt
Labels: feat

#160 merge: (#159) 최고 관리자 로그인 오류 해결
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCase.kt
Labels: bug, refactor

#161 merge: (#158) Domain Properties 초기화 전체 적용
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/SendAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddIndividualScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeIndividualScheduleUseCaseTest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/EntireSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeProfileImageUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckEmailDuplicationUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/UserInfoUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/global/DomainPropertiesInitialization.kt
  simtong-application/src/test/kotlin/team/comit/simtong/global/annotation/SimtongTest.kt
Labels: refactor, test
