Repository Team-ComIT/SimTong-Backend, pull requests merged in 2023-01, with the labels that each got.

#266 merge: (#264) 디바이스 토큰 저장
  .github/workflows/dev-cd.yml
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/AdminSignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignUpRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/UserSignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandDeviceTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/DeviceToken.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/DeviceTokenMapper.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
Labels: feat, refactor

#268 알림 기능 추가
  .github/workflows/CI.yml
  .github/workflows/build.yml
  .github/workflows/dev-cd.yml
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/AdminSignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignUpRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/UserSignInRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/CommandDeviceTokenPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/spi/UserPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/DeviceToken.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/security/SecurityConfig.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/DeviceTokenMapper.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
Labels: feat, refactor

#270 merge: (#269) 에러 로깅
  .github/workflows/CI.yml
  .github/workflows/build.yml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/filter/ExceptionFilter.kt
  simtong-infrastructure/src/main/resources/application.yml
Labels: feat

#273 merge: (#272) 회원가입 닉네임 필수
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SendEmailPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignUpRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/NickNamePort.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
Labels: refactor

#274 release(닉네임 필수 적용): 1.2.1
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/spi/SendEmailPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/SignUpRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/NickNamePort.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
Labels: refactor

#276 merge: (#275) Index 설정
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/entity/EmployeeCertificateJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/entity/ScheduleJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
Labels: performance

#277 release(DB 인덱스 추가): 1.2.2
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/entity/EmployeeCertificateJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/entity/ScheduleJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/entity/UserJpaEntity.kt
Labels: performance

#279 merge: (#278) 코드 스타일 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/CommandEmployeeCertificatePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/CommandMenuPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/CommandNotificationPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/exception/GlobalExceptions.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/extension/QuerydslExtensionUtils.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/GenericMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayPeriodMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/NotificationPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationReceiverMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/mapper/ScheduleMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/entity/SpotJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/entity/TeamJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/template/MailTemplate.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/exception/WebFileExceptions.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/value/WebHolidayQueryType.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/value/WebHolidayStatus.kt
Labels: refactor

#282 merge: (#280) 요청 값 객체 추가
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/GlobalErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/parser/ExcelFileAdapter.kt
  simtong-infrastructure/src/main/resources/application-dev.yml
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ChangePasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/CheckMatchedAccountWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ResetPasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/converter/FileConverter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/ChangeNicknameWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/value/EmployeeNumber.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/value/NickName.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/value/Password.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtils.kt
Labels: feat, refactor

#284 merge: (#283) LocalDateTime 예외 처리
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/GlobalErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
Labels: refactor

#285 release(매핑 스타일 리팩토링, DDD스러운 코드): 1.2.3
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/spi/CommandEmployeeCertificatePort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/CommandHolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/spi/CommandMenuPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/spi/CommandNotificationPort.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/GlobalErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/exception/GlobalExceptions.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/extension/QuerydslExtensionUtils.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/GenericMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodeLimitPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/AuthCodePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/EmployeeCertificatePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPeriodPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayPeriodMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/MenuPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/NotificationPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationReceiverMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/SchedulePersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/mapper/ScheduleMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/SpotPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/entity/SpotJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/TeamPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/entity/TeamJpaEntity.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/UserPersistenceAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/AwsSESAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/email/template/MailTemplate.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/notification/FcmAdapter.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/thirdparty/parser/ExcelFileAdapter.kt
  simtong-infrastructure/src/main/resources/application-dev.yml
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ChangePasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/CheckMatchedAccountWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/ResetPasswordWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/converter/FileConverter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/exception/WebFileExceptions.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/value/WebHolidayQueryType.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/value/WebHolidayStatus.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/ChangeNicknameWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/request/SignUpWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/value/EmployeeNumber.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/value/NickName.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/value/Password.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/global/RegexUtils.kt
Labels: feat, refactor

#288 merge: (#287) Value Class 오류 수정
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/request/CheckMatchedAccountWebRequest.kt
Labels: bug

#292 merge: (#286) AuthCode, AuthCodeLimit 도메인 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/ReissueTokenUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/SendAuthCodeUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/SendAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCodeLimit.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/AuthCodeMapper.kt
Labels: refactor

#293 merge: (#291) mapper 직접 구현
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyVersions.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-infrastructure/build.gradle.kts
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/AuthCodeLimitMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/auth/mapper/RefreshTokenMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/file/mapper/EmployeeCertificateMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayPeriodMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/menu/mapper/MenuMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/notification/mapper/NotificationReceiverMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/mapper/ScheduleMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/spot/mapper/SpotMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/team/mapper/TeamMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/DeviceTokenMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
Labels: refactor

#294 merge: (#286) Holiday 도메인 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryRemainAnnualUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/HolidayQueryType.kt
Labels: refactor

#298 merge: (#286) Schedule 도메인 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/AddIndividualScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeIndividualScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/QueryEntireSpotScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveIndividualScheduleUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeIndividualScheduleUseCaseTest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/model/Schedule.kt
  simtong-infrastructure/build.gradle.kts
Labels: refactor

#299 merge: (#286) 도메인 용어 적용
  simtong-application/src/main/kotlin/team/comit/simtong/domain/spot/usecase/ShowSpotListUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/team/usecase/QueryTeamsUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CancelHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryIndividualHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeIndividualScheduleUseCaseTest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveIndividualScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/holiday/model/Holiday.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/schedule/model/Schedule.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/DeviceToken.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/spi/.gitkeep
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/mapper/HolidayMapper.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/schedule/mapper/ScheduleMapper.kt
Labels: refactor

#302 merge: (#281) 표현 계층 도메인 의존성 추가
  simtong-presentation/build.gradle.kts
Labels: setting

#307 merge: (#286) User 도메인 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeProfileImageUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckEmailDuplicationUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckMatchedAccountUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/CheckNicknameDuplicationUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ComparePasswordUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/QueryAdminInfoUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/QueryUserInfoUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointAnnualUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayPeriodUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/AppointHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ChangeEmployeeHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/CheckHolidayPeriodUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryMonthHolidayPeriodUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/ShareHolidayUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddIndividualScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/AddSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeIndividualScheduleUseCaseTest.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/ChangeSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/QueryIndividualSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveIndividualScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/schedule/usecase/RemoveSpotScheduleUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/AdminSignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeEmailUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeNicknameUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangePasswordUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeProfileImageUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ChangeSpotUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ComparePasswordUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/QueryAdminInfoUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/QueryUserInfoUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/ResetPasswordUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignInUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/SignUpUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/DeviceToken.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/EmployeeNumber.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/NickName.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/Password.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/user/model/User.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/user/mapper/UserMapper.kt
Labels: refactor

#305 merge: (#281) Notification & Menu Dto 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/SaveMenuRequest.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/request/SaveMenuData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/response/MenuResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryMenuByMonthUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/QueryPublicMenuUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/dto/request/SendNotificationData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/notification/usecase/SendNotificationUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCaseTests.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/WebMenuAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/dto/SaveMenuRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/dto/request/SaveMenuWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/NotificationWebAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/WebNotificationAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/SendNotificationRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/SendNotificationWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/WebNotificationType.kt
Labels: refactor

#308 merge: (#281) 파일 & 이메일 & 관리자 dto 리팩토링
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/dto/request/CheckAuthCodeData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/dto/request/SendAuthCodeData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/SendAuthCodeUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/dto/response/UploadImageListResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/dto/response/UploadImageResponse.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/SendAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/file/usecase/UploadImageUseCaseTests.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/WebAdminAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/AdminSignInRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/request/SignInWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/WebEmailAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/dto/CheckAuthCodeRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/dto/SendAuthCodeRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/dto/request/SendAuthCodeWebRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/dto/response/.gitkeep
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/dto/request/.gitkeep
Labels: refactor

#310 merge: 도메인 주도적 함수 명으로 변경
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/spi/QueryHolidayPort.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/holiday/usecase/QueryEmployeeHolidayUseCaseTests.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/persistence/holiday/HolidayPersistenceAdapter.kt
Labels: refactor

#311 merge: (#301) Request 개선
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/dto/request/CheckAuthCodeData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/dto/request/SaveMenuData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCase.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/dto/request/FindEmployeeNumberData.kt
  simtong-application/src/main/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCase.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/auth/usecase/CheckAuthCodeUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/menu/usecase/SaveMenuUseCaseTests.kt
  simtong-application/src/test/kotlin/team/comit/simtong/domain/user/usecase/FindEmployeeNumberUseCaseTests.kt
  simtong-domain/src/main/kotlin/team/comit/simtong/domain/auth/model/AuthCode.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/WebErrorHandler.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/CustomFieldError.kt
  simtong-infrastructure/src/main/kotlin/team/comit/simtong/global/error/dto/ErrorResponse.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/admin/dto/AdminSignInRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/WebCommonAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/ChangePasswordRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/FindEmployeeNumberRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/common/dto/ResetPasswordRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/WebEmailAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/dto/CheckAuthCodeRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/email/dto/SendAuthCodeRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/file/WebFileAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/WebHolidayAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/AppointAnnualRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/AppointHolidayPeriodRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/AppointHolidayRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/CancelHolidayRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/ChangeEmployeeHolidayRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/holiday/dto/ShareHolidayRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/WebMenuAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/menu/dto/SaveMenuRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/notification/dto/SendNotificationRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/WebScheduleAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/dto/AddIndividualScheduleRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/dto/AddSpotScheduleRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/dto/ChangeIndividualScheduleRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/schedule/dto/ChangeSpotScheduleRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/WebUserAdapter.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeEmailRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeNicknameRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeProfileImageRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/ChangeSpotRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/SignUpRequest.kt
  simtong-presentation/src/main/kotlin/team/comit/simtong/domain/user/dto/UserSignInRequest.kt
Labels: performance, refactor
